const Map<String, String> homeEnUS = {
  'home': 'Home',
  'notification': 'Notifications',
  'app': 'Tiền Giang',
  'setting': 'Settings',
  'menu': 'Menu',
  'profile': 'Profile',
  'qr scan': 'QR Scan',
  'reflect': 'Reflect',
  'prevention': 'Prevention',
  'covid advise': 'Covid advise',
  'need info': 'Need info',
  'government': 'Government',
  'news': 'News',
  'camera': 'Camera',
  'public service': 'Public service',
  'hotline': 'Hotline',
  'land': 'Land',
  'traffic': 'Traffic',
  'payment': 'Payment',
  'travel': 'Travel',
  'medical': 'Medical',
  'enviroment': 'Enviroment',
  'other utilities': 'Other utilities',
  'social': 'Social',
  'education': 'Education',
  'economy': 'Economy',
};
