final Map<String, String> homeEnUS = {
  'Home': 'Home',
  'Notification': 'Notifications',
  'App': 'Tiền Giang',
  'Setting': 'Settings',
  'Menu': 'Menu',
  'Profile': 'Profile',
  'QR Scan': 'QR Scan',
  'Reflect': 'Reflect',
  'Prevention': 'Prevention',
  'Covid advise': 'Covid advise',
  'Need info': 'Need info',
  'Government': 'Government',
  'News': 'News',
  'Camera': 'Camera',
  'Public service': 'Public service',
  'Hotline': 'Hotline',
  'Land': 'Land',
  'Traffic': 'Traffic',
  'Payment': 'Payment',
  'Travel': 'Travel',
  'Medical': 'Medical',
  'Enviroment': 'Enviroment',
  'Other utilities': 'Other utilities',
  'Social': 'Social',
  'Education': 'Education',
  'Economy': 'Economy',
  'Sign in': 'Sign in', //
  'View profile': 'View profile',
};
