const Map<String, String> homeViVN = {
  'home': 'Trang chủ',
  'notification': 'Thông báo',
  'app': 'Tiền Giang',
  'setting': 'Cài đặt',
  'menu': 'Menu',
  'profile': 'Hồ sơ cá nhân',
  'qr scan': 'Quét mã QR',
  'reflect': 'Phản ánh',
  'prevention': 'Phòng chống dịch bệnh',
  'covid advise': 'Tư vấn covid',
  'need info': 'Thông tin cần biết',
  'government': 'Chính phủ',
  'news': 'Tin tức',
  'camera': 'Camera',
  'public service': 'Dịch vụ công',
  'hotline': 'Đường dây nóng khẩn cấp',
  'land': 'Đất đai',
  'traffic': 'Giao thông',
  'payment': 'Thanh toán',
  'travel': 'Du lịch',
  'medical': 'Y tế',
  'enviroment': 'Môi trường',
  'other utilities': 'Tiện ích khác',
  'social': 'An sinh xã hội',
  'education': 'Giáo dục',
  'economy': 'Kinh tế',
};
