final Map<String, String> homeViVN = {
  'Home': 'Trang chủ',
  'Notification': 'Thông báo',
  'App': 'Tiền Giang',
  'Setting': 'Cài đặt',
  'Menu': 'Menu',
  'Profile': 'Hồ sơ cá nhân',
  'QR Scan': 'Quét mã QR',
  'Reflect': 'Phản ánh',
  'Prevention': 'Phòng chống dịch bệnh',
  'Covid advise': 'Tư vấn covid',
  'Need info': 'Thông tin cần biết',
  'Government': 'Chính phủ',
  'News': 'Tin tức',
  'Camera': 'Camera',
  'Public service': 'Dịch vụ công',
  'Hotline': 'Đường dây nóng khẩn cấp',
  'Land': 'Đất đai',
  'Traffic': 'Giao thông',
  'Payment': 'Thanh toán',
  'Travel': 'Du lịch',
  'Medical': 'Y tế',
  'Enviroment': 'Môi trường',
  'Other utilities': 'Tiện ích khác',
  'Social': 'An sinh xã hội',
  'Education': 'Giáo dục',
  'Economy': 'Kinh tế',
};
